CREATE TABLE sensor_mac (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    sensor_id NVARCHAR(16) NOT NULL UNIQUE,
    sensor_mac NVARCHAR(17) NOT NULL UNIQUE,
    row_version TIMESTAMP NOT NULL,
);